FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /app

COPY *.sln ./
COPY BookStore.Models/BookStore.Models.csproj ./BookStore.Models/
COPY BookStore.Utility/BookStore.Utility.csproj ./BookStore.Utility/
COPY BookStore.DataAccess/BookStore.DataAccess.csproj ./BookStore.DataAccess/
COPY BookStore.Web/BookStore.Web.csproj ./BookStore.Web/

RUN dotnet restore

COPY . .

RUN dotnet build --no-restore -c Release

RUN dotnet publish -c Release -o /out --no-restore

FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS runtime
WORKDIR /app
COPY --from=build /out .

ENV ASPNETCORE_URLS=http://+:5000
ENV DOTNET_RUNNING_IN_CONTAINER=true

EXPOSE 5000
ENTRYPOINT ["dotnet", "BookStore.Web.dll"]
